version: '3'
services:
  dolphin-dashboard-backend-php:
    build: .
    volumes:
      - "./src:/app"
  dolphin-dashboard-backend-db:

    image: mariadb:10
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file: src/.env
    hostname: dolphin-dashboard-backend-db
    ports:
      - "43832:3306"
volumes:
  dbdata:
