version: '3'
services:
  dolphin-dashboard-backend-php:
    build: .
    volumes:
      - "./src:/app"
    networks:
      - dolphin-dashbord
    depends_on:
      - dolphin-dashboard-backend-db
  dolphin-dashboard-backend-db:
    image: mariadb:10
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file: src/.env
    hostname: dolphin-dashboard-backend-db
    ports:
      - "43832:3306"
    networks:
      - dolphin-dashbord
volumes:
  dbdata:
networks:
  dolphin-dashbord:
